### ISSUE TITLE
数学公式渲染报错

### ISSUE THREAD

**Issue by unlimitedLoop** [akuma/evermark#50]
我的笔记里，有的包含了大量的数学公式，使用的是MathJax 语法，在发布的时候，会报错，但是我又不知道具体错在哪里

**Comment by unlimitedLoop** [comment]
补上错误栈
```
Unknown character (2): U+4EE3 in MathJax_Main,MathJax_Size1,MathJax_AMS
Unknown character (2): U+8868 in MathJax_Main,MathJax_Size1,MathJax_AMS
ERROR  TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:289:26)
    at exports.spawn (child_process.js:380:9)
    at Object.exports.execFile (child_process.js:143:15)
    at Object.execFile (/home/xiang/.npm-packages/lib/node_modules/evermark/node_modules/.1.0.0@pn/_promisify.js:35:27)
    at Promise.resolve.then (/home/xiang/.npm-packages/lib/node_modules/evermark/node_modules/.4.1.1@svg2png/lib/svg2png.js:13:33)
```

**Comment by akuma** [comment]
你可以给出一个简短的测试用例吗？
